version: 0.0
os: linux
files:
  - source: docker-compose.yml
    destination: /home/ubuntu
    overwrite: true  # Ensure this overwrites the existing file
  - source: start.sh
    destination: /home/ubuntu
    overwrite: true  # Ensure this overwrites the existing file
 

hooks:

  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: root
