version: 0.0
os: linux
files:
  - source: docker-compose.yml
    destination: /home/ec2-user/
    overwrite: true   # Add this line to overwrite the existing file
  - source: scripts/start_containers.sh
    destination: /home/ec2-user/
    overwrite: true   # Add this line to overwrite the existing file
  - source: scripts/stop_containers.sh
    destination: /home/ec2-user/
    overwrite: true   # Add this line to overwrite the existing file

hooks:
  BeforeInstall:
    - location: scripts/stop_containers.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_containers.sh
      timeout: 300
      runas: root
